services:
  - type: web
    name: scelto-poker
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm build && pnpm db:deploy && pnpm db:seed
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: APP_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_EMAIL
        value: mailto:admin@scelto.no
      - key: VITE_VAPID_PUBLIC_KEY
        sync: false
